name: weather_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  go_router: ^11.1.2
  openapi_generator: ^4.13.1
  http: ^1.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  lottie: ^2.6.0
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  
openapi_generator:
  generator-cli-version: '5.0.0'
  spec: openapi.json
  output: lib/api

