// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUxZOwyGvMB-otNg92EYadQEzbfj3baZ8',
    appId: '1:320942276003:web:b19b5ac93afc2f333bee16',
    messagingSenderId: '320942276003',
    projectId: 'weather-app-ac8b1',
    authDomain: 'weather-app-ac8b1.firebaseapp.com',
    storageBucket: 'weather-app-ac8b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpT9W3ZbHHjnmYrkNu5NDXMco-gDuxOG8',
    appId: '1:320942276003:android:f4a92ddb676d31243bee16',
    messagingSenderId: '320942276003',
    projectId: 'weather-app-ac8b1',
    storageBucket: 'weather-app-ac8b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBqBd01jWlq4I8Ubr4f46o6gNfqCNnrpU',
    appId: '1:320942276003:ios:234fdf9245bbdba63bee16',
    messagingSenderId: '320942276003',
    projectId: 'weather-app-ac8b1',
    storageBucket: 'weather-app-ac8b1.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
